### ISSUE TITLE
Why do we need a cache at all eventually?

### ISSUE THREAD

**Issue by sergiogiogio** [alex-phillips/node-clouddrive#12]
Could we drop the cache? I understand from the API that it is possible to search a node by name and parent node, so to reach a "folder" we just need to issue as many requests as the folder's depth.

It would simplify the project a lot.

https://drive.amazonaws.com/drive/v1/nodes?filters=name:FolderName AND parentsId:ParentId

**Comment by alex-phillips** [comment]
I think it's work writing functions that talk to the API directly instead of utilizing the cache (maybe an override flag parameter for each function?), but I think there is too much benefit to having a cache to ultimately get rid of it completely.
1. It provides offline actions for anything that doesn't involve altering your clouddrive (i.e., searching).
2. Other operations would not be possible at all without potentially hundreds (or more) API calls (`disk usage`, `tree`, etc.).
3. Speed. Even operations such as `resolve` where we construct the string path of a node would require one API call for each level down the node is. This can get expensive not only when considering API calls, but network request time as well.

Any thoughts on these are more than welcome, but I don't see this application getting rid of the cache while staying fast and feature-rich.

**Comment by sergiogiogio** [comment]
Sorry for the late reply. Here are my thoughts:

1- searching can be done with the /nodes?filters= API
2- disk usage and tree can probably be done with the same API (1 call only then go through all the pages).
3- resolve requires one API call per level, agree.

I agree that a cache is necessary when there are a lot of calls, which is the case for the FUSE driver since most unix utilities expect that file operations are quick and issue generous number of them. In the case of clouddrive commands we know we operate on the clould and we are smart to only issue the absolutely necessary file operations.

Once you have the cache, you have the issue of synchronization. In our case we need to decide when to sync and being out of sync may create many silent issues for the user. On the development side it also make the code more complex and adds dependencies.

However I understand your comment about how the cache is already part of the user interface of the application so it would not make sense to drop it now.

[1] https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes

**Comment by alex-phillips** [comment]
@sergiogiogio I agree with some of your points. I think it would be beneficial to add functionality for direct API calls if the developer decides to not implement a caching mechanism. I'll work on adding this in a future release. But as far as the CLI app packaged with this project, I don't think that should move away from the cache.

**Comment by alex-phillips** [comment]
Just an update on this - I'm slowly adding support for functions (and CLI commands) to optionally pass in a `remote` flag that will force the code to talk via the API rather than rely on the local cache.

**Comment by alex-phillips** [comment]
Going to close this. I've added support for the `--remote` flag on some commands, but depending on the amount of requests required for some functions (i.e., `tree`, `ls`, etc.) this can easily run up the request limit and return a 429. Caching will be necessary for speed and API limitations.
